title: Sugawara Lab.
description: Sugawara Laborory at the University of Electro-Communications since 2017.
show_downloads: true
google_analytics: UA-189789020-1
theme: jekyll-theme-cayman
lang: ja
permalink: /:categories/:title
collections:
  member:
    output: true
    permalink: /member/:title
