version: '3'

services:
  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jekyll
    volumes:
      - .:/src
    tty: true
    ports:
      - 5555:5555
    working_dir: /src
    command: /bin/bash